name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greetings 
        run: echo "Hello Buddy"
      - name: Print goodbye
        run: echo "bye bye buddy"
      
